version: '3'

services:
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Metodo@7195
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: tcc
      MYSQL_PASSWORD: Metodo@7195
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    networks:
      - tcc-network
    volumes:
      - ./data:/var/lib/mysql


  back-end:
    container_name: backend
    build: ./back-end
    volumes:
      - ./images:/public/images/produto:rw
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '8080:8080'
    expose:
      - '8080'
    restart: always
    depends_on:
      - db
    networks:
      - tcc-network
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: Metodo@7195
      DB_NAME: ecommerce

  # vue-front:
  #   build: ./vue-front
  #   restart: always
  #   depends_on:
  #     - back-end

  # react-front:
  #   build: ./react-front
  #   restart: always
  #   depends_on:
  #     - back-end

  # angular-front:
  #   build: ./angular-front
  #   restart: always
  #   depends_on:
  #     - back-end

networks:
  tcc-network:
    driver: bridge